In [15]:
import pandas as pd
import numpy as np

class MissingValueHandler:
    def __init__(self, file_path):
        self.file_path = file_path
        self.data = self.read_file(file_path)

    def change_budget(self, df, column_name):
        if column_name in df.columns:
            df[column_name] = df[column_name].round().astype(float)

    def validate_data_types(self, data):
        for column in data.columns:
            if data[column].dtype == 'int64' or data[column].dtype == 'float64':
                data[column] = pd.to_numeric(data[column], errors='coerce')
            elif data[column].dtype == 'object':
                data[column] = data[column].astype(str)
        return data

    def read_file(self, file_path):
        garbage_values = ["n/a", "na", "--", "—", ",", ".", "*"]
        data = pd.read_csv(file_path, na_values=garbage_values)
        data = self.validate_data_types(data)
        self.change_budget(data, 'Budget in USD')
        return data

    def print_modified_rows(self, original_df, modified_df):
        modified_rows = original_df.ne(modified_df).any(axis=1)
        if modified_rows.any():
            print(modified_df[modified_rows])
        else:
            print("No modified rows found.")

    def impute_mean(self, df):
        df_imputed = df.copy()
        for column in df_imputed.columns:
            if df_imputed[column].dtype in ['float64', 'int64']:
                df_imputed[column].fillna(df_imputed[column].mean(), inplace=True)
        self.change_budget(df_imputed, 'Budget in USD')
        return df_imputed

    def impute_median(self, df):
        df_imputed = df.copy()
        for column in df_imputed.columns:
            if df_imputed[column].dtype in ['float64', 'int64']:
                df_imputed[column].fillna(df_imputed[column].median(), inplace=True)
        self.change_budget(df_imputed, 'Budget in USD')
        return df_imputed

    def impute_mode(self, df):
        df_imputed = df.copy()
        for column in df_imputed.columns:
            if df_imputed[column].dtype in ['float64', 'int64']:
                df_imputed[column].fillna(df_imputed[column].mode()[0], inplace=True)
        self.change_budget(df_imputed, 'Budget in USD')
        return df_imputed

    def impute_constant(self, df, value):
        df_imputed = df.copy()
        df_imputed.fillna(value, inplace=True)
        self.change_budget(df_imputed, 'Budget in USD')
        return df_imputed

    def impute_ffill(self, df):
        df_ffill = df.ffill()
        self.change_budget(df_ffill, 'Budget in USD')
        return df_ffill

    def impute_bfill(self, df):
        df_bfill = df.bfill()
        self.change_budget(df_bfill, 'Budget in USD')
        return df_bfill

    def drop_missing_rows(self, df):
        return df.dropna()

    def drop_missing_columns(self, df):
        return df.dropna(axis=1)

Original Data:
Mean:
     Unnamed: 0   Movie Id            Genre Release Date    Rating  \
52           28  JDIKIDDGY            Drama   17/12/1991  9.901920
59           38  ZCKFMPWZL          Musical   13/01/2006  4.496297
65           31  QKPWRHWCW        Adventure   14/12/1986  9.034368
118          77  RBUVAOLXJ           Sports   26/08/2006  9.781337
133          82  SHWNLGZNU            Drama   29/04/1995  7.900184
144          36  HSELIBSUI          Mystery   15/03/1984  9.924358
176          52  KRNDDCERL         Thriller   25/11/2014  9.448966
282          53  PERNNBIJB        Animation   29/10/2008  8.476273
333          28  YHZKCSHGI            Drama   03/11/2018  5.828396
360          64  TFCQUJXPV        Adventure   04/02/1983  8.971272
413          94  TQICNAYOM          Mystery   11/04/2001  8.490931
481          91  PTBNNYJAZ        Adventure   05/03/2005  8.755281
487           9  MDTSJQLOG           Comedy   26/05/2020  9.380835
549          46  OUROXXLLF            Drama   23/10/1990  9.233227
708          63  ONLWCXARO      Documentary   25/02/2012  3.215218
769           2  FDJXRNXAU          Fantasy   27/07/1987  9.665568
784          50  BEJLMXPDE           Horror   29/01/1995  7.716055
863           5  CLJHIWBGH            Crime   07/05/2018  9.956385
922          91  PODVAPPAJ        Adventure   18/09/2010  8.753690
930          11  FUPNZFLVS  Science Fiction   13/10/1989  8.431474

                                               Summary Shooting Location  \
52   A talented young musician struggles to overcom...            Sydney
59   A heartwarming documentary film about a group ...             Tokyo
65   A group of survivors must navigate a treachero...           Toronto
118  A suspenseful horror film that will leave you ...          New York
133  A high-powered lawyer takes on a seemingly unw...            London
144  When a series of strange events plague a small...             Tokyo
176  In a kingdom plagued by darkness, a young prin...          New York
282  A captivating musical film that will transport...             Tokyo
333  A talented young musician struggles to overcom...           Toronto
360  A lost civilization is rediscovered deep withi...             Tokyo
413  In a future where emotions are outlawed, a reb...            London
481  A group of explorers ventures deep into the Am...       Los Angeles
487  A heartwarming story about a dog who brings tw...             Paris
549  A documentary film that sheds light on a socia...             Paris
708  A historical drama that sheds light on a signi...       Los Angeles
769  A legendary swordsman embarks on a quest to av...       Los Angeles
784  A young girl with extraordinary powers must le...            London
863  A captivating foreign film that showcases the ...             Tokyo
922  A group of explorers ventures deep into the Am...          New York
930  A group of friends embark on a hilarious road ...             Tokyo

     Budget in USD  Awards  Popular
52      47637004.0       2        0
59      47637004.0       0        0
65      47637004.0       2        0
118     47637004.0       1        0
133     47637004.0       0        0
144     47637004.0       1        0
176     47637004.0       1        0
282     47637004.0       2        0
333     47637004.0       0        0
360     47637004.0       2        0
413     47637004.0       2        0
481     47637004.0       2        0
487     47637004.0       2        0
549     47637004.0       2        0
708     47637004.0       0        0
769     47637004.0       2        0
784     47637004.0       0        0
863     47637004.0       1        0
922     47637004.0       2        0
930     47637004.0       2        0
Median:
     Unnamed: 0   Movie Id            Genre Release Date    Rating  \
52           28  JDIKIDDGY            Drama   17/12/1991  9.901920
59           38  ZCKFMPWZL          Musical   13/01/2006  4.496297
65           31  QKPWRHWCW        Adventure   14/12/1986  9.034368
118          77  RBUVAOLXJ           Sports   26/08/2006  9.781337
133          82  SHWNLGZNU            Drama   29/04/1995  7.900184
144          36  HSELIBSUI          Mystery   15/03/1984  9.924358
176          52  KRNDDCERL         Thriller   25/11/2014  9.448966
282          53  PERNNBIJB        Animation   29/10/2008  8.476273
333          28  YHZKCSHGI            Drama   03/11/2018  5.828396
360          64  TFCQUJXPV        Adventure   04/02/1983  8.971272
413          94  TQICNAYOM          Mystery   11/04/2001  8.490931
481          91  PTBNNYJAZ        Adventure   05/03/2005  8.755281
487           9  MDTSJQLOG           Comedy   26/05/2020  9.380835
549          46  OUROXXLLF            Drama   23/10/1990  9.233227
708          63  ONLWCXARO      Documentary   25/02/2012  3.215218
769           2  FDJXRNXAU          Fantasy   27/07/1987  9.665568
784          50  BEJLMXPDE           Horror   29/01/1995  7.716055
863           5  CLJHIWBGH            Crime   07/05/2018  9.956385
922          91  PODVAPPAJ        Adventure   18/09/2010  8.753690
930          11  FUPNZFLVS  Science Fiction   13/10/1989  8.431474

                                               Summary Shooting Location  \
52   A talented young musician struggles to overcom...            Sydney
59   A heartwarming documentary film about a group ...             Tokyo
65   A group of survivors must navigate a treachero...           Toronto
118  A suspenseful horror film that will leave you ...          New York
133  A high-powered lawyer takes on a seemingly unw...            London
144  When a series of strange events plague a small...             Tokyo
176  In a kingdom plagued by darkness, a young prin...          New York
282  A captivating musical film that will transport...             Tokyo
333  A talented young musician struggles to overcom...           Toronto
360  A lost civilization is rediscovered deep withi...             Tokyo
413  In a future where emotions are outlawed, a reb...            London
481  A group of explorers ventures deep into the Am...       Los Angeles
487  A heartwarming story about a dog who brings tw...             Paris
549  A documentary film that sheds light on a socia...             Paris
708  A historical drama that sheds light on a signi...       Los Angeles
769  A legendary swordsman embarks on a quest to av...       Los Angeles
784  A young girl with extraordinary powers must le...            London
863  A captivating foreign film that showcases the ...             Tokyo
922  A group of explorers ventures deep into the Am...          New York
930  A group of friends embark on a hilarious road ...             Tokyo

     Budget in USD  Awards  Popular
52      47731306.0       2        0
59      47731306.0       0        0
65      47731306.0       2        0
118     47731306.0       1        0
133     47731306.0       0        0
144     47731306.0       1        0
176     47731306.0       1        0
282     47731306.0       2        0
333     47731306.0       0        0
360     47731306.0       2        0
413     47731306.0       2        0
481     47731306.0       2        0
487     47731306.0       2        0
549     47731306.0       2        0
708     47731306.0       0        0
769     47731306.0       2        0
784     47731306.0       0        0
863     47731306.0       1        0
922     47731306.0       2        0
930     47731306.0       2        0
Mode:
     Unnamed: 0   Movie Id            Genre Release Date    Rating  \
52           28  JDIKIDDGY            Drama   17/12/1991  9.901920
59           38  ZCKFMPWZL          Musical   13/01/2006  4.496297
65           31  QKPWRHWCW        Adventure   14/12/1986  9.034368
118          77  RBUVAOLXJ           Sports   26/08/2006  9.781337
133          82  SHWNLGZNU            Drama   29/04/1995  7.900184
144          36  HSELIBSUI          Mystery   15/03/1984  9.924358
176          52  KRNDDCERL         Thriller   25/11/2014  9.448966
282          53  PERNNBIJB        Animation   29/10/2008  8.476273
333          28  YHZKCSHGI            Drama   03/11/2018  5.828396
360          64  TFCQUJXPV        Adventure   04/02/1983  8.971272
413          94  TQICNAYOM          Mystery   11/04/2001  8.490931
481          91  PTBNNYJAZ        Adventure   05/03/2005  8.755281
487           9  MDTSJQLOG           Comedy   26/05/2020  9.380835
549          46  OUROXXLLF            Drama   23/10/1990  9.233227
708          63  ONLWCXARO      Documentary   25/02/2012  3.215218
769           2  FDJXRNXAU          Fantasy   27/07/1987  9.665568
784          50  BEJLMXPDE           Horror   29/01/1995  7.716055
863           5  CLJHIWBGH            Crime   07/05/2018  9.956385
922          91  PODVAPPAJ        Adventure   18/09/2010  8.753690
930          11  FUPNZFLVS  Science Fiction   13/10/1989  8.431474

                                               Summary Shooting Location  \
52   A talented young musician struggles to overcom...            Sydney
59   A heartwarming documentary film about a group ...             Tokyo
65   A group of survivors must navigate a treachero...           Toronto
118  A suspenseful horror film that will leave you ...          New York
133  A high-powered lawyer takes on a seemingly unw...            London
144  When a series of strange events plague a small...             Tokyo
176  In a kingdom plagued by darkness, a young prin...          New York
282  A captivating musical film that will transport...             Tokyo
333  A talented young musician struggles to overcom...           Toronto
360  A lost civilization is rediscovered deep withi...             Tokyo
413  In a future where emotions are outlawed, a reb...            London
481  A group of explorers ventures deep into the Am...       Los Angeles
487  A heartwarming story about a dog who brings tw...             Paris
549  A documentary film that sheds light on a socia...             Paris
708  A historical drama that sheds light on a signi...       Los Angeles
769  A legendary swordsman embarks on a quest to av...       Los Angeles
784  A young girl with extraordinary powers must le...            London
863  A captivating foreign film that showcases the ...             Tokyo
922  A group of explorers ventures deep into the Am...          New York
930  A group of friends embark on a hilarious road ...             Tokyo

     Budget in USD  Awards  Popular
52         11498.0       2        0
59         11498.0       0        0
65         11498.0       2        0
118        11498.0       1        0
133        11498.0       0        0
144        11498.0       1        0
176        11498.0       1        0
282        11498.0       2        0
333        11498.0       0        0
360        11498.0       2        0
413        11498.0       2        0
481        11498.0       2        0
487        11498.0       2        0
549        11498.0       2        0
708        11498.0       0        0
769        11498.0       2        0
784        11498.0       0        0
863        11498.0       1        0
922        11498.0       2        0
930        11498.0       2        0
Constant:
     Unnamed: 0   Movie Id            Genre Release Date    Rating  \
52           28  JDIKIDDGY            Drama   17/12/1991  9.901920
59           38  ZCKFMPWZL          Musical   13/01/2006  4.496297
65           31  QKPWRHWCW        Adventure   14/12/1986  9.034368
118          77  RBUVAOLXJ           Sports   26/08/2006  9.781337
133          82  SHWNLGZNU            Drama   29/04/1995  7.900184
144          36  HSELIBSUI          Mystery   15/03/1984  9.924358
176          52  KRNDDCERL         Thriller   25/11/2014  9.448966
282          53  PERNNBIJB        Animation   29/10/2008  8.476273
333          28  YHZKCSHGI            Drama   03/11/2018  5.828396
360          64  TFCQUJXPV        Adventure   04/02/1983  8.971272
413          94  TQICNAYOM          Mystery   11/04/2001  8.490931
481          91  PTBNNYJAZ        Adventure   05/03/2005  8.755281
487           9  MDTSJQLOG           Comedy   26/05/2020  9.380835
549          46  OUROXXLLF            Drama   23/10/1990  9.233227
708          63  ONLWCXARO      Documentary   25/02/2012  3.215218
769           2  FDJXRNXAU          Fantasy   27/07/1987  9.665568
784          50  BEJLMXPDE           Horror   29/01/1995  7.716055
863           5  CLJHIWBGH            Crime   07/05/2018  9.956385
922          91  PODVAPPAJ        Adventure   18/09/2010  8.753690
930          11  FUPNZFLVS  Science Fiction   13/10/1989  8.431474

                                               Summary Shooting Location  \
52   A talented young musician struggles to overcom...            Sydney
59   A heartwarming documentary film about a group ...             Tokyo
65   A group of survivors must navigate a treachero...           Toronto
118  A suspenseful horror film that will leave you ...          New York
133  A high-powered lawyer takes on a seemingly unw...            London
144  When a series of strange events plague a small...             Tokyo
176  In a kingdom plagued by darkness, a young prin...          New York
282  A captivating musical film that will transport...             Tokyo
333  A talented young musician struggles to overcom...           Toronto
360  A lost civilization is rediscovered deep withi...             Tokyo
413  In a future where emotions are outlawed, a reb...            London
481  A group of explorers ventures deep into the Am...       Los Angeles
487  A heartwarming story about a dog who brings tw...             Paris
549  A documentary film that sheds light on a socia...             Paris
708  A historical drama that sheds light on a signi...       Los Angeles
769  A legendary swordsman embarks on a quest to av...       Los Angeles
784  A young girl with extraordinary powers must le...            London
863  A captivating foreign film that showcases the ...             Tokyo
922  A group of explorers ventures deep into the Am...          New York
930  A group of friends embark on a hilarious road ...             Tokyo

     Budget in USD  Awards  Popular
52           777.0       2        0
59           777.0       0        0
65           777.0       2        0
118          777.0       1        0
133          777.0       0        0
144          777.0       1        0
176          777.0       1        0
282          777.0       2        0
333          777.0       0        0
360          777.0       2        0
413          777.0       2        0
481          777.0       2        0
487          777.0       2        0
549          777.0       2        0
708          777.0       0        0
769          777.0       2        0
784          777.0       0        0
863          777.0       1        0
922          777.0       2        0
930          777.0       2        0
Forward Fill:
     Unnamed: 0   Movie Id            Genre Release Date    Rating  \
52           28  JDIKIDDGY            Drama   17/12/1991  9.901920
59           38  ZCKFMPWZL          Musical   13/01/2006  4.496297
65           31  QKPWRHWCW        Adventure   14/12/1986  9.034368
118          77  RBUVAOLXJ           Sports   26/08/2006  9.781337
133          82  SHWNLGZNU            Drama   29/04/1995  7.900184
144          36  HSELIBSUI          Mystery   15/03/1984  9.924358
176          52  KRNDDCERL         Thriller   25/11/2014  9.448966
282          53  PERNNBIJB        Animation   29/10/2008  8.476273
333          28  YHZKCSHGI            Drama   03/11/2018  5.828396
360          64  TFCQUJXPV        Adventure   04/02/1983  8.971272
413          94  TQICNAYOM          Mystery   11/04/2001  8.490931
481          91  PTBNNYJAZ        Adventure   05/03/2005  8.755281
487           9  MDTSJQLOG           Comedy   26/05/2020  9.380835
549          46  OUROXXLLF            Drama   23/10/1990  9.233227
708          63  ONLWCXARO      Documentary   25/02/2012  3.215218
769           2  FDJXRNXAU          Fantasy   27/07/1987  9.665568
784          50  BEJLMXPDE           Horror   29/01/1995  7.716055
863           5  CLJHIWBGH            Crime   07/05/2018  9.956385
922          91  PODVAPPAJ        Adventure   18/09/2010  8.753690
930          11  FUPNZFLVS  Science Fiction   13/10/1989  8.431474

                                               Summary Shooting Location  \
52   A talented young musician struggles to overcom...            Sydney
59   A heartwarming documentary film about a group ...             Tokyo
65   A group of survivors must navigate a treachero...           Toronto
118  A suspenseful horror film that will leave you ...          New York
133  A high-powered lawyer takes on a seemingly unw...            London
144  When a series of strange events plague a small...             Tokyo
176  In a kingdom plagued by darkness, a young prin...          New York
282  A captivating musical film that will transport...             Tokyo
333  A talented young musician struggles to overcom...           Toronto
360  A lost civilization is rediscovered deep withi...             Tokyo
413  In a future where emotions are outlawed, a reb...            London
481  A group of explorers ventures deep into the Am...       Los Angeles
487  A heartwarming story about a dog who brings tw...             Paris
549  A documentary film that sheds light on a socia...             Paris
708  A historical drama that sheds light on a signi...       Los Angeles
769  A legendary swordsman embarks on a quest to av...       Los Angeles
784  A young girl with extraordinary powers must le...            London
863  A captivating foreign film that showcases the ...             Tokyo
922  A group of explorers ventures deep into the Am...          New York
930  A group of friends embark on a hilarious road ...             Tokyo

     Budget in USD  Awards  Popular
52      67899080.0       2        0
59      82727451.0       0        0
65      85405233.0       2        0
118     29503043.0       1        0
133     52284629.0       0        0
144     11633113.0       1        0
176     61742981.0       1        0
282     88210342.0       2        0
333     38028397.0       0        0
360      3139807.0       2        0
413     73985548.0       2        0
481     34055448.0       2        0
487     29436686.0       2        0
549     20902011.0       2        0
708     38352058.0       0        0
769     70372854.0       2        0
784     68317061.0       0        0
863     44844376.0       1        0
922     86897843.0       2        0
930     10583491.0       2        0
Backward Fill :
     Unnamed: 0   Movie Id            Genre Release Date    Rating  \
52           28  JDIKIDDGY            Drama   17/12/1991  9.901920
59           38  ZCKFMPWZL          Musical   13/01/2006  4.496297
65           31  QKPWRHWCW        Adventure   14/12/1986  9.034368
118          77  RBUVAOLXJ           Sports   26/08/2006  9.781337
133          82  SHWNLGZNU            Drama   29/04/1995  7.900184
144          36  HSELIBSUI          Mystery   15/03/1984  9.924358
176          52  KRNDDCERL         Thriller   25/11/2014  9.448966
282          53  PERNNBIJB        Animation   29/10/2008  8.476273
333          28  YHZKCSHGI            Drama   03/11/2018  5.828396
360          64  TFCQUJXPV        Adventure   04/02/1983  8.971272
413          94  TQICNAYOM          Mystery   11/04/2001  8.490931
481          91  PTBNNYJAZ        Adventure   05/03/2005  8.755281
487           9  MDTSJQLOG           Comedy   26/05/2020  9.380835
549          46  OUROXXLLF            Drama   23/10/1990  9.233227
708          63  ONLWCXARO      Documentary   25/02/2012  3.215218
769           2  FDJXRNXAU          Fantasy   27/07/1987  9.665568
784          50  BEJLMXPDE           Horror   29/01/1995  7.716055
863           5  CLJHIWBGH            Crime   07/05/2018  9.956385
922          91  PODVAPPAJ        Adventure   18/09/2010  8.753690